### ISSUE TITLE
keyError 'data_time'

### ISSUE THREAD

**Issue by JJY0710** [NVlabs/SegFormer#131]
During the validation process has keyerror data_time

Traceback (most recent call last):
  File "/home/project/JT/SegFormer/tools/train.py", line 166, in <module>
    main()
  File "/home/project/JT/SegFormer/tools/train.py", line 155, in main
    train_segmentor(
  File "/home/project/JT/SegFormer/mmseg/apis/train.py", line 115, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/home/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/hooks/logger/base.py", line 153, in after_train_iter
    self.log(runner)
  File "/home/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/hooks/logger/text.py", line 234, in log
    self._log_info(log_dict, runner)
  File "/home/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/hooks/logger/text.py", line 154, in _log_info
    f'data_time: {log_dict["data_time"]:.3f}, '
KeyError: 'data_time'

**Comment by gewenchao** [comment]
I delete                 log_str += f'time: {log_dict["time"]:.3f}, ' \
                           f'data_time: {log_dict["data_time"]:.3f}, '

**Comment by JJY0710** [comment]
When delete     log_str += f'time: {log_dict["time"]:.3f}, ' \
                           f'data_time: {log_dict["data_time"]:.3f}, '
return to normal，what's problem?

**Comment by congcongwy51** [comment]
请问您解决了吗
