### ISSUE TITLE
Error: AlignedResize is not in the pipeline registry

### ISSUE THREAD

**Issue by cyrilzakka** [NVlabs/SegFormer#2]
Currently trying to run the evaluation script:
`python tools/test.py local_configs/segformer/B1/segformer.b1.512x512.ade.160k.py /path/to/checkpoint_file`

results in the following error: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/content/mmsegmentation/mmseg/datasets/pipelines/test_time_aug.py", line 59, in __init__
    self.transforms = Compose(transforms)
  File "/content/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'AlignedResize is not in the pipeline registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/content/mmsegmentation/mmseg/datasets/ade.py", line 91, in __init__
    **kwargs)
  File "/content/mmsegmentation/mmseg/datasets/custom.py", line 88, in __init__
    self.pipeline = Compose(pipeline)
  File "/content/mmsegmentation/mmseg/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "MultiScaleFlipAug: 'AlignedResize is not in the pipeline registry'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 166, in <module>
    main()
  File "tools/test.py", line 122, in main
    dataset = build_dataset(cfg.data.test)
  File "/content/mmsegmentation/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'ADE20KDataset: "MultiScaleFlipAug: \'AlignedResize is not in the pipeline registry\'"'
```
as `AlignedResize` seems to be missing an import in `SegFormer/mmseg/datasets/pipelines/__init__.py`. This pull request adds the import accordingly.

**Comment by xieenze** [comment]
Thanks to fix the bug
