### ISSUE TITLE
 Default process group is not initialized

### ISSUE THREAD

**Issue by abbhinavvenkat** [NVlabs/SegFormer#23]
I'm trying to run the training code as follows: 
`python tools/train.py local_configs/segformer/B0/segformer.b0.512x512.ade.160k.py`

I've changed the dataset to a custom dataset (the one given in the [OpenMMLab Tutorial](https://github.com/NVlabs/SegFormer/blob/69ec8f96db97e6d6ecbfcd5f40250de031574c30/demo/MMSegmentation_Tutorial.ipynb)) 

Getting the below error. The tutorial notebook works fine in the original OpenMMLab repo. Do you have any insight into why this might be happening and what I have to change to make it run? 

```
Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta)
  File "/content/mmsegmentation/mmseg/apis/train.py", line 115, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/iter_based_runner.py", line 131, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/content/mmsegmentation/mmseg/models/segmentors/base.py", line 152, in train_step
    losses = self(**data_batch)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/content/mmsegmentation/mmseg/models/segmentors/base.py", line 122, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/content/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 158, in forward_train
    gt_semantic_seg)
  File "/content/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 102, in _decode_head_forward_train
    self.train_cfg)
  File "/content/mmsegmentation/mmseg/models/decode_heads/decode_head.py", line 188, in forward_train
    seg_logits = self.forward(inputs)
  File "/content/mmsegmentation/mmseg/models/decode_heads/segformer_head.py", line 82, in forward
    _c = self.linear_fuse(torch.cat([_c4, _c3, _c2, _c1], dim=1))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/bricks/conv_module.py", line 195, in forward
    x = self.norm(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/batchnorm.py", line 519, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 638, in get_world_size
    return _get_group_size(group)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 220, in _get_group_size
    _check_default_pg()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 211, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```

**Comment by xieenze** [comment]
Please refer to #12

**Comment by sharat29ag** [comment]
@abbhinavvenkat, have you solved this error? Were you using single GPU?
