### ISSUE TITLE
Fp16OptimizerHook breaks training

### ISSUE THREAD

**Issue by damonmaria** [NVlabs/SegFormer#38]
First off, thanks for your awesome work.

I have no trouble getting SegFormer to train normally but if I configure with `Fp16OptimizerHook` then a short way into training (10-20k iterations) suddenly no classes are predicted:
```python
optimizer_config=dict(type="Fp16OptimizerHook"),
fp16=dict(),
```

Is this expected? Has anyone got `Fp16OptimizerHook` to work with this repo?

**Comment by damonmaria** [comment]
My initial comment was with the B4 network. I've since tried B5 and instead get the following error:
```
Traceback (most recent call last):
--
File "train-defect-model-node.py", line 62, in <module>
main(**vars(parser.parse_args()))
File "train-defect-model-node.py", line 47, in main
train_segmentor(
File "/opt/conda/lib/python3.8/site-packages/mmseg/apis/train.py", line 115, in train_segmentor
runner.run(data_loaders, cfg.workflow)
File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 131, in run
iter_runner(iter_loaders[i], **kwargs)
File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
self.call_hook('after_train_iter')
File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 308, in call_hook
getattr(hook, fn_name)(self)
File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/hooks/optimizer.py", line 130, in after_train_iter
scaled_loss.backward()
File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([2, 3072, 160, 160], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(3072, 768, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
ConvolutionParams
data_type = CUDNN_DATA_HALF
padding = [0, 0, 0]
stride = [1, 1, 0]
dilation = [1, 1, 0]
groups = 1
deterministic = false
allow_tf32 = true
input: TensorDescriptor 0x560be0726ba0
type = CUDNN_DATA_HALF
nbDims = 4
dimA = 2, 3072, 160, 160,
strideA = 78643200, 25600, 160, 1,
output: TensorDescriptor 0x7f31d0016c20
type = CUDNN_DATA_HALF
nbDims = 4
dimA = 2, 768, 160, 160,
strideA = 19660800, 25600, 160, 1,
weight: FilterDescriptor 0x7f31d003f660
type = CUDNN_DATA_HALF
tensor_format = CUDNN_TENSOR_NCHW
nbDims = 4
dimA = 768, 3072, 1, 1,
Pointer addresses:
input: 0x7f31fa5ca000
output: 0x7f320f74a000
weight: 0x7f337ed00000
terminate called after throwing an instance of 'c10::Error'
what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1603729096996/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f352984d8b2 in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f3529a9f982 in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f3529838b7d in /opt/conda/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5f65b2 (0x7f352a6c85b2 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5f6666 (0x7f352a6c8666 in /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x1c0eb9 (0x560b7b4afeb9 in /opt/conda/bin/python)
frame #6: <unknown function> + 0x127f83 (0x560b7b416f83 in /opt/conda/bin/python)
frame #7: <unknown function> + 0x127f83 (0x560b7b416f83 in /opt/conda/bin/python)
frame #8: <unknown function> + 0x1285b5 (0x560b7b4175b5 in /opt/conda/bin/python)
frame #9: <unknown function> + 0x1c0d74 (0x560b7b4afd74 in /opt/conda/bin/python)
frame #10: <unknown function> + 0x1284e6 (0x560b7b4174e6 in /opt/conda/bin/python)
frame #11: <unknown function> + 0x1c0d74 (0x560b7b4afd74 in /opt/conda/bin/python)
frame #12: <unknown function> + 0x11c5a6 (0x560b7b40b5a6 in /opt/conda/bin/python)
frame #13: <unknown function> + 0x128ac6 (0x560b7b417ac6 in /opt/conda/bin/python)
frame #14: <unknown function> + 0x128a7c (0x560b7b417a7c in /opt/conda/bin/python)
frame #15: <unknown function> + 0x128a7c (0x560b7b417a7c in /opt/conda/bin/python)
frame #16: PyDict_SetItem + 0x2ac (0x560b7b46035c in /opt/conda/bin/python)
frame #17: PyDict_SetItemString + 0x4f (0x560b7b460a4f in /opt/conda/bin/python)
frame #18: PyImport_Cleanup + 0x9b (0x560b7b53adfb in /opt/conda/bin/python)
frame #19: Py_FinalizeEx + 0x83 (0x560b7b53b1b3 in /opt/conda/bin/python)
frame #20: Py_RunMain + 0x110 (0x560b7b53d6a0 in /opt/conda/bin/python)
frame #21: Py_BytesMain + 0x39 (0x560b7b53d829 in /opt/conda/bin/python)
frame #22: __libc_start_main + 0xe7 (0x7f3534338b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #23: <unknown function> + 0x1deb33 (0x560b7b4cdb33 in /opt/conda/bin/python)
```

**Comment by xieenze** [comment]
Hi,
Sorry I haven't used FP16 in mmsegmentation. Not sure which part has problem.
