### ISSUE TITLE
无法通过预训练模型完成训练

### ISSUE THREAD

**Issue by heblade** [NVlabs/SegFormer#45]
预训练模型路径：
./SegFormer/checkpoints/pretrained/mit_b1.pth
执行脚本：
cd SegFormer

python ./tools/train.py ./local_configs/segformer/B1/segformer.b1.512x512.ade.160k.py 
报错信息：
Traceback (most recent call last):
  File "c:\xxxx\github\mmcv\mmcv\utils\registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "C:\xxxx\github\torch_env\lib\site-packages\mmseg\models\segmentors\encoder_decoder.py", line 30, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "C:\xxxx\github\torch_env\lib\site-packages\mmseg\models\builder.py", line 17, in build_backbone
    return BACKBONES.build(cfg)
  File "c:\xxxx\github\mmcv\mmcv\utils\registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "c:\xxxx\github\mmcv\mmcv\cnn\builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "c:\xxxx\github\mmcv\mmcv\utils\registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'mit_b1 is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train.py", line 166, in <module>
    main()
  File "./tools/train.py", line 135, in main
    test_cfg=cfg.get('test_cfg'))
  File "C:\xxxx\github\torch_env\lib\site-packages\mmseg\models\builder.py", line 46, in build_segmentor
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "c:\xxxx\github\mmcv\mmcv\utils\registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "c:\xxxx\github\mmcv\mmcv\cnn\builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "c:\xxxx\github\mmcv\mmcv\utils\registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "EncoderDecoder: 'mit_b1 is not in the models registry'"

请问大神如何解决该问题？
mmcv-full, mmsegmentation以及您的SegFormer是否需要通过特定的代码版本一一对应才行？

**Comment by TBD1** [comment]
我也遇到这个问题了，请问您解决了吗？

**Comment by Aitong1018** [comment]
执行 pip install -e . --user 即可

**Comment by wujiang0156** [comment]
@ZhaoNan1  yes, you are right

**Comment by FanoShannon** [comment]
how to fix OSError: EncoderDecoder: pretrained/mit_b5.pth is not a checkpoint file

**Comment by annanya-tamu** [comment]
1. Download a .pth file from [here](https://connecthkuhk-my.sharepoint.com/personal/xieenze_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fxieenze%5Fconnect%5Fhku%5Fhk%2FDocuments%2Fsegformer%2Fpretrained%5Fmodels&ga=1)
2. Then create a pretrained/ folder inside Segformer folder. (Should look like /path/to/Segformer/pretrained).
3. Move the .pth file from the first step to the pretrained/ folder created in the second step. 
4. Run `python ./tools/train.py ./local_configs/segformer/B1/segformer.b1.512x512.ade.160k.py
` again
