### ISSUE TITLE
Issue in the beginning

### ISSUE THREAD

**Issue by npy-sjh** [NVlabs/SegFormer#46]
Hi, guys. I ran into an issue at the very beginning.
You can see it below.
Any advice?

Traceback (most recent call last):
  File "tools/test.py", line 10, in <module>
    from mmseg.apis import multi_gpu_test, single_gpu_test
  File "D:\Conda\envs\torch\lib\site-packages\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "D:\Conda\envs\torch\lib\site-packages\mmseg\apis\inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "D:\Conda\envs\torch\lib\site-packages\mmseg\models\__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "D:\Conda\envs\torch\lib\site-packages\mmseg\models\backbones\__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "D:\Conda\envs\torch\lib\site-packages\mmseg\models\backbones\fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "D:\Conda\envs\torch\lib\site-packages\mmseg\models\decode_heads\__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "D:\Conda\envs\torch\lib\site-packages\mmseg\models\decode_heads\cc_head.py", line 7, in <module>
    from mmcv.ops import CrissCrossAttention
  File "D:\Conda\envs\torch\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "D:\Conda\envs\torch\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "D:\Conda\envs\torch\lib\site-packages\mmcv\utils\ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Conda\envs\torch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed

**Comment by npy-sjh** [comment]
Never mind, try Linux.
