### ISSUE TITLE
assert palette.shape[0] == len(self.CLASSES)

### ISSUE THREAD

**Issue by AhmadZobairSurosh** [NVlabs/SegFormer#93]
I used the following command for visualization, but got the following error.
"""
python demo/image_demo.py data/fp_grayscale/fp/images/validation/389808-2model.jpg local_configs/segformer/B4/segformer.b4.512x512.fp.40k_single-gpu.py work_dirs/segformer.b4.512x512.fp.40k_single-gpu/iter_26000.pth  --device cuda:0 --palette fp

Use load_from_local loader
Traceback (most recent call last):
  File "demo/image_demo.py", line 29, in <module>
    main()
  File "demo/image_demo.py", line 25, in main
    show_result_pyplot(model, args.img, result, get_palette(args.palette))
  File "/mnt/sdc/zobair/floor-plans/segformer/SegFormer/mmseg/apis/inference.py", line 115, in show_result_pyplot
    img = model.show_result(img, result, palette=palette, show=False)
  File "/mnt/sdc/zobair/floor-plans/segformer/SegFormer/mmseg/models/segmentors/base.py", line 246, in show_result
    assert palette.shape[0] == len(self.CLASSES)
AssertionError"""

any Ideas what might be the cause and how can it be solved!

Thanks in advance

**Comment by SAWRJJ** [comment]
Hello. I meet the same problem. Have you solved it?

**Comment by avigupta2798** [comment]
Pallete type you are sending must have same number in the shape as the number of classes in the config selecting.

**Comment by QuietWoods** [comment]
Comment on this line of code,it works for me.
```
        # assert palette.shape[0] == len(self.CLASSES)
        assert palette.shape[1] == 3
        assert len(palette.shape) == 2
```

**Comment by AirHighway** [comment]
When I use image_demo.py, I meet the same problem.

The "config" parameter, I use "segformer.b1.512x512.ade.160k.py", but "palette" parameter, I use "cityscapes". 

So change the "palette" parameter from "cityscapes" to "ade" can solve this problem. 

The main key is "palette", other errors like "assert palette.shape[0] == len(self.CLASSES)" occur, you need to check and change "palette" in the python file.

![problem 1](https://github.com/NVlabs/SegFormer/assets/86967582/036e88c5-8ed3-4cb9-85a8-873467d29335)

**Comment by AirHighway** [comment]
![problem 1](https://github.com/NVlabs/SegFormer/assets/86967582/cbe43dc0-039b-4096-886e-028187178463)

**Comment by YznMur** [comment]
https://github.com/NVlabs/SegFormer/assets/56399611/f7305aec-9a94-44a9-ae96-ab157c0fc5b6
